language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - git clone https://github.com/iblancasa/ghrankings.git generated
  - make
  - make spain-region
after_success:
  - git config --global user.email "iblancasa@gmail.com"
  - git config --global user.name "Israel Blancas"
  - cd generated; git add *; git commit -m "New rankings generated"; git push https://${ACCESS}@github.com/iblancasa/ghrankings.git master
